name: Deploy to Github Pages
on:
    push:
        branches:
          - main

jobs:
    build-site:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Configurar Python
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
                  cache: "pip"

            - name: Install Dependencies
              run: pip install -r requirements.txt

            # Configurar Quarto
            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2  

            # Construir Jupyter Book
            - name: Build Jupyter Book Documentation
              run: jupyter-book build docs/

            # Renderizar archivos .qmd con Quarto
            - name: Render Quarto files
              run: quarto render

            # Consolidar ambos outputs en un solo directorio
            - name: Move Quarto and JupyterBook output
              run: |
                  mkdir -p public
                  cp -r docs/_build/html/* public/
                  cp -r _site/* public/

            # Subir artefacto para despliegue
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              if: github.ref == 'refs/heads/main'
              with:
                  path: "public"

    deploy-site:
        needs: build-site
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Github Pages
              id: deployment
              uses: actions/deploy-pages@v4
